### PR TITLE
:sparkles: Week of Jan 31st Changes

### PR DESCRIPTION
**Pull request by Chrono-byte**
#### Summary:
Updates for controller display and disable the decorative display when under competition control

Additionally includes changes to autonomi and adds a new autonomous

Updates some formatting

#### Motivation:
A new background task that updates the controller screen allows for fewer errors in matches with the wrong auton being selected.

Disables decorative War Games when under competition control to optimize memory usage.

#### Test Plan:

- [x] Have code reviewed by @MrEnderman10 
- [x] Deploy code on V5 brain and test changes

### CODE REVIEW

**Review by Chrono-byte — COMMENTED** [review]
These changes all worked last night at the league.

**Review by Chrono-byte — COMMENTED** [review]
Fixed workflow and more fixes to auton related code

**Review by Chrono-byte — COMMENTED** [review]
review my own code haha

**Review by MrEnderman10 — APPROVED** [review]
sauton seems good

**Pull request merged**
